2024-05-03 20:57:26,497 - DEBUG - Path does not exist: /path/to/custom/utils/bin
2024-05-03 20:57:26,497 - DEBUG - Path does not exist: /path/to/custom/python/bin
2024-05-03 20:57:26,497 - DEBUG - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:03:37,285 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:04:24,094 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:07:21,257 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:08:10,872 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:09:38,975 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:10:14,727 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:11:21,223 - ERROR - An error occurred: PathCompiler.__init__() got an unexpected keyword argument 'logger'
2024-05-03 21:11:39,128 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:13:10,880 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:13:39,479 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:13:39,479 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:13:39,479 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:13:39,479 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:50:40,590 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:50:40,591 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:50:40,591 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:50:40,591 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:55:06,385 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:55:06,385 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:55:06,386 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:55:06,386 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:55:47,555 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:55:47,556 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:55:47,556 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:55:47,556 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:57:30,516 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:57:30,516 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:57:30,516 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:57:30,517 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 21:59:36,541 - INFO - Starting compilation of paths from path.ini
2024-05-03 21:59:36,542 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 21:59:36,542 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 21:59:36,542 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:06:06,545 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:06:06,545 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:06:06,546 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:06:06,546 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:09:12,938 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:09:12,938 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:09:12,938 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:09:12,938 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:11:55,277 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:11:55,277 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:11:55,277 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:11:55,278 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:13:28,470 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:13:28,470 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:13:28,470 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:13:28,470 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:16:53,799 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:16:53,800 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:16:53,800 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:16:53,800 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:36:40,123 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:36:40,123 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:36:40,123 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:36:40,124 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
2024-05-03 22:39:00,884 - INFO - Starting compilation of paths from path.ini
2024-05-03 22:39:00,885 - ERROR - Path does not exist: /path/to/custom/utils/bin
2024-05-03 22:39:00,885 - ERROR - Path does not exist: /path/to/custom/python/bin
2024-05-03 22:39:00,885 - ERROR - Path does not exist: /path/to/custom/nodejs/bin
